<?php
return [
    'missing' => [
        'carte_key' => 'Nenhuma chave de carte encontrada, clique no botão carte abaixo para digitar uma.',
        'config_key' => 'Falta a chave [%s] necessária em %s',
    ],
    'date' => [
        'tomorrow' => 'Amanhã',
        'yesterday' => 'Ontem',
        'full' => '%s até %s',
        'today' => 'Hoje',
    ],
    'php' => [
        'date_format' => 'd M A',
        'date_time_format_long' => 'l,jS F Y \a\t h:i a',
    ],
    'moment' => [
        'date_format_long' => 'dddd, de MMM AAAA',
        'date_time_format_short' => 'DD MMM \à\s HH:mm',
        'date_time_format_long' => 'dddd, de MMMM AAAA \à\s HH:mm a',
        'day_time_format' => 'DD ddd hh:mm a',
    ],
    'countries' => [
        'text_title' => 'Países',
        'text_form_name' => 'País',
        'text_filter_search' => 'Pesquisar por nome ou código.',
        'text_empty' => 'Não há países disponíveis.',
        'label_priority' => 'Prioridade',
        'label_format' => 'Formato',
        'help_format' => 'Endereço = {address_1}<br />Bairro = {address_2}<br />Cidade = {city}<br />CEP = {postcode}<br />Estado = {state}<br />País = {country}',
        'help_iso' => 'Saiba mais sobre <a target="_blank" href="http://en.wikipedia.org/wiki/ISO_3166-1"> ISO Alpha 2 & 3</a>',
        'alert_set_default' => 'Country set as default',
        'column_status' => 'Status',
    ],
    'currencies' => [
        'text_title' => 'Moedas',
        'text_form_name' => 'Moeda',
        'text_filter_search' => 'Pesquisar por nome ou código.',
        'text_empty' => 'Não há moedas disponíveis.',
        'text_right' => 'Direita',
        'text_left' => 'Esquerda',
        'column_code' => 'Código',
        'column_country' => 'País',
        'column_symbol' => 'Símbolo',
        'column_rate' => 'Taxa',
        'column_status' => 'Status',
        'label_title' => 'Título',
        'label_code' => 'Código',
        'label_country' => 'País',
        'label_symbol' => 'Símbolo',
        'label_symbol_position' => 'Posição do Símbolo',
        'label_rate' => 'Taxa',
        'label_thousand_sign' => 'Separador de Milhares',
        'label_decimal_sign' => 'Ponto Decimal',
        'label_decimal_position' => 'Casas decimais',
        'help_iso' => 'Saiba mais sobre <a target="_blank" href="https://en.wikipedia.org/wiki/ISO_4217">ISO 4217</a>',
        'alert_set_default' => 'Currency set as default',
    ],
    'extensions' => [
        'text_title' => 'Extenções',
        'text_delete_title' => 'Extensão: Excluir',
        'text_filter_search' => 'Pesquisar por nome.',
        'text_empty' => 'Não há extensões disponíveis.',
        'text_installed' => 'Instalado',
        'text_uninstalled' => 'Desinstalado',
        'text_files' => 'arquivos',
        'text_files_data' => 'arquivos e dados',
        'text_settings' => 'Configurações',
        'text_author' => 'Autor',
        'button_browse' => '<i class="fa fa-globe"></i>&nbsp;&nbsp;Browse more extensions&nbsp;&nbsp;<i class="fa fa-external-link-alt"></i>',
        'button_delete' => 'Excluir',
        'button_yes_delete' => 'Sim, excluir',
        'button_return_to_list' => 'Não, voltar para a lista',
        'column_icon' => 'Ícone',
        'column_version' => 'Versão',
        'label_delete_data' => 'Excluir dados',
        'error_config_no_found' => 'Ocorreu um erro, o arquivo de registro da extensão não pôde ser encontrado',
        'alert_info_layouts' => '<b>Layout e componentes da página registrados</b>',
        'alert_warning_layouts' => 'Para exibir o componente para esta extensão em uma página, adicione-o a um layout <a href="%s" class="alert-link">aqui!</a>',
        'alert_delete_warning' => 'Você está prestes a excluir o %s de extensão <b>%s</b>',
        'alert_delete_confirm' => 'Tem certeza de que deseja excluir o associado %s? Isso não pode ser desfeito!',
        'alert_is_installed' => '. Você deve desinstalar uma extensão antes de excluir.',
        'alert_setting_missing_id' => 'Código de configuração da extensão não foi especificado.',
        'alert_setting_not_found' => 'Configurações da extensão não foram encontradas.',
        'alert_setting_model_missing' => 'Faltando modelo de configurações.',
        'alert_setting_model_not_found' => 'Modelo de configurações da extensão [%s] não foi encontrado.',
        'alert_is_required' => 'This extension cannot be uninstalled as it is required by the system. You may run composer remove command to remove the extension files.',
    ],
    'languages' => [
        'text_title' => 'Línguas',
        'text_form_name' => 'Idioma',
        'text_tab_general' => 'Detalhes',
        'text_tab_files' => 'Traduções',
        'text_tab_edit_file' => 'Editar traduções',
        'text_filter_search' => 'Pesquisar por nome.',
        'text_empty' => 'Não há idiomas disponíveis.',
        'text_empty_translations' => 'Não há traduções disponíveis.',
        'text_files' => 'arquivos',
        'text_current_build' => 'Current build: %s',
        'text_no_update_available' => '(%s) is up to date',
        'column_code' => 'Código',
        'column_status' => 'Status',
        'column_variable' => 'Texto de origem (inglês)',
        'column_language' => 'Texto de tradução (%s)',
        'label_code' => 'Código local',
        'label_image' => 'Ícone',
        'label_check_updates' => 'Check for updates',
        'button_browse' => '<i class="fa fa-globe"></i>&nbsp;&nbsp;Browse more languages&nbsp;&nbsp;<i class="fa fa-external-link-alt"></i>',
        'translations' => [
            'label_file' => 'Arquivo de localização',
            'label_search' => 'Procurar',
            'help_no_files' => 'Nenhuma tradução correspondente foi encontrada para este idioma. Você deve instalar um pacote de idioma.',
        ],
        'text_filter_file' => 'Exibir todos os grupos',
        'text_filter_translations' => 'Search translations by key or text',
        'text_locale_strings' => 'Total: %s, translated: %s (%s%%), untranslated %s',
        'text_title_update_available' => 'New translation strings are available for (%s).',
        'text_update_available' => 'Only the translation strings that haven’t been modified will be updated.',
        'text_publish_translations' => 'Publish translations',
        'button_apply_update' => '<i class="fa fa-cloud-download"></i>&nbsp;&nbsp;Download new translated strings',
        'button_import_translations' => 'Import translations',
        'button_publish_translations' => 'Publish translations',
        'help_language' => 'Usar um código de localidade completa (por exemplo, "fr_FR") em vez de apenas um código de idioma genérico (por exemplo, "fr"), deve ser o mesmo que o diretório de localidade.',
        'help_locale_strings' => 'Make sure NOT to translate placeholders like <b>%s</b> or <b>:name</b>. Leave them as is.',
        'help_publish_translations' => 'If you want your translations included in the core or extension release, please upload them to the <a href="%s" target="_blank">Crowdin project.</a> They will be reviewed by the Core Team or the Extension Author.',
        'alert_set_default' => 'Language set as default',
        'alert_update_complete' => '%s: Translation strings for (%s) have been updated.',
        'alert_language_not_found' => 'Language not found',
        'alert_publish_success' => 'Translations published successfully',
    ],
    'mail_templates' => [
        'text_title' => 'Layouts de e-mail',
        'text_form_name' => 'Layout De E-Mail',
        'text_template_title' => 'Modelos de e-mail',
        'text_new_template_title' => 'Modelo de e-mail: Novo',
        'text_edit_template_title' => 'Modelo de e-mail: Atualizar',
        'text_preview_template_title' => 'Modelo de e-mail: Pré-visualizar',
        'text_partial_title' => 'Parciais de e-mail',
        'text_partial_form_name' => 'E-mail parcial',
        'text_new_partial_title' => 'E-mail Parcial: Novo',
        'text_edit_partial_title' => 'E-mail Parcial: Atualizar',
        'text_preview_partial_title' => 'E-mail Parcial: Pré-visualização',
        'text_templates' => 'Modelos',
        'text_layouts' => 'Layouts',
        'text_partials' => 'Parciais',
        'text_empty' => 'Não há modelos de e-mail disponíveis.',
        'text_variables' => 'Variáveis',
        'text_internal' => 'Mensagem interna',
        'text_contact' => 'E-mail de contato para o administrador',
        'button_test_message' => 'Enviar mensagem de teste',
        'column_code' => 'Código',
        'column_title' => 'Título',
        'column_layout' => 'Layout',
        'column_status' => 'Status',
        'label_language' => 'Idioma',
        'label_code' => 'Código',
        'label_subject' => 'Assunto',
        'label_layout' => 'Layout',
        'label_layout_css' => 'Layout CSS',
        'label_body' => 'HTML',
        'label_markdown' => 'Markdown',
        'label_plain' => 'Texto Simple',
        'help_variables' => 'Arraste essas variáveis para a área de conteúdo:',
        'alert_test_message_sent' => 'Mensagem de teste enviada com sucesso para %s',
        'alert_template_id_not_found' => 'Template id not found',
        'alert_template_not_found' => ' Template not found',
    ],
    'mail_variables' => [
        'text_group_global' => 'Variaveis Globais',
        'text_site_name' => 'Nome do site',
        'text_site_logo' => 'Logotipo do site',
        'text_group_customer' => 'Variáveis do cliente',
        'text_first_name' => 'Nome do cliente',
        'text_last_name' => 'Sobrenome do cliente',
        'text_email' => 'Endereço de e-mail do cliente',
        'text_telephone' => 'Telefone do cliente',
        'text_group_registration' => 'Variáveis de registro',
        'text_account_login_link' => 'URL de login da conta',
        'text_group_reset' => 'Variáveis de redefinição de senha',
        'text_reset_code' => 'Código de redefinição da senha',
        'text_reset_link' => 'URL de redefinição de senha',
        'text_group_order' => 'Variáveis do pedido',
        'text_order_object' => 'Order model object',
        'text_order_number' => 'Número do pedido',
        'text_customer_name' => 'Nome completo do cliente',
        'text_order_type' => 'Tipo de pedido ex. entrega/retirada',
        'text_order_time' => 'Tempo de entrega/retirada do pedido',
        'text_order_date' => 'Data de entrega/retirada do pedido',
        'text_order_added' => 'Data de criação do pedido',
        'text_order_payment' => 'Método de pagamento do pedido',
        'text_order_address' => 'Endereço do cliente para entrega do pedido',
        'text_invoice_number' => 'Telefone do cliente',
        'text_invoice_date' => 'Telefone do cliente',
        'text_order_menus' => 'Lista da ordem dos itens do menu',
        'text_order_comment' => 'Comentário do pedido',
        'text_location_logo' => 'Location logo',
        'text_location_name' => 'Nome do local',
        'text_location_email' => 'E-mail do local',
        'text_location_address' => 'Endereço do local',
        'text_location_telephone' => 'Location telephone',
        'text_order_view_url' => 'URL para visualizar pedido',
        'text_order_totals' => 'Lista dos totais do pedido',
        'text_menu_name' => 'Nome do menu do pedido',
        'text_menu_quantity' => 'Quantidade do menu do pedido',
        'text_menu_price' => 'Preço do menu de pedido',
        'text_menu_subtotal' => 'Subtotal do menu do pedido',
        'text_menu_options' => 'Opção do menu do pedido ex. nome: preço',
        'text_menu_comment' => 'Comentário do menu do pedido',
        'text_order_total_title' => 'Título total do pedido',
        'text_order_total_value' => 'Valor total do pedido',
        'text_priority' => 'Prioridade total do pedido',
        'text_group_reservation' => 'Variáveis de reserva',
        'text_reservation_object' => 'Reservation model object',
        'text_reservation_number' => 'Número de reserva',
        'text_reservation_date' => 'Data da reserva',
        'text_reservation_time' => 'Tempo de reserva',
        'text_reservation_guest_no' => 'Número de convidados reservados',
        'text_reservation_comment' => 'Comentário da reserva',
        'text_reservation_view_url' => 'URL da visualização da reserva',
        'text_status_name' => 'Nome da Situação',
        'text_status_comment' => 'Comentário da situação',
        'text_group_stock' => 'Stock variables',
        'text_stock_name' => 'Stock name',
        'text_stock_quantity' => 'Stock quantity',
        'text_low_stock_threshold' => 'Low stock threshold',
        'text_stock_object' => 'Stock model object',
        'text_group_contact' => 'Variáveis do contato',
        'text_full_name' => 'Nome completo do contato',
        'text_contact_email' => 'E-mail do contato',
        'text_contact_telephone' => 'Telefone do contato',
        'text_contact_topic' => 'Tópico do contato',
        'text_contact_message' => 'Corpo da mensagem do contato',
        'text_group_staff_reset' => 'User password reset variables',
        'text_staff_name' => 'User name',
        'text_staff_reset_link' => 'User password reset url',
    ],
    'permissions' => [
        'countries' => 'Criar, editar e excluir países',
        'currencies' => 'Criar, editar e excluir moedas',
        'system_logs' => 'Ver logs do sistema e requisições',
        'extensions' => 'Instalar, desinstalar e excluir extensão',
        'mail_templates' => 'Criar, editar e excluir modelos de e-mail',
        'languages' => 'Criar, editar e excluir idiomas do site',
        'settings' => 'Gerenciar configurações do sistema',
        'updates' => 'Capacidade de aplicar as atualizações quando uma nova versão do TastyIgniter estiver disponível',
        'name' => 'Avançado',
        'notifications' => 'Access and manage notifications',
    ],
    'request_logs' => [
        'text_title' => 'Logs de requisições',
        'text_form_name' => 'Log de Requisição',
        'text_filter_search' => 'Pesquisar por nome.',
        'text_empty' => 'Não há registros de requisições disponíveis.',
        'text_empty_referrer' => 'Não há referenciadores para esta URL.',
        'column_status_code' => 'Código da Situação',
        'column_url' => 'URL Solicitada',
        'column_count' => 'Contador',
        'label_url' => 'URL Solicitada',
        'label_referer' => 'Referência',
    ],
    'settings' => [
        'text_title' => 'Configurações',
        'text_edit_title' => 'Configurações: %s',
        'text_tab_general' => 'Geral',
        'text_tab_site' => 'Localization',
        'text_tab_restaurant' => 'Restaurante',
        'text_tab_mail' => 'E-mail',
        'text_tab_server' => 'Avançado',
        'text_tab_desc_general' => 'Configure your restaurant name, email, logo and geolocation settings',
        'text_tab_desc_site' => 'Configure your site default country, language, currency and timezone settings.',
        'text_tab_desc_mail' => 'Configurações para envio de e-mails',
        'text_tab_desc_server' => 'Gerenciar configurações avançadas do sistema como habilitar/desabilitar manutenção.',
        'text_tab_title_maps' => 'Geolocalização',
        'text_tab_title_date_time' => 'Data/Hora',
        'text_tab_title_currency' => 'Moeda',
        'text_tab_title_language' => 'Idioma',
        'text_tab_title_maintenance' => 'Manutenção',
        'text_tab_title_system_log' => 'Configurações de Log',
        'text_tab_title_activity_log' => 'Configurações da Atividade do Log',
        'text_single' => 'Único',
        'text_multiple' => 'Múltiplo',
        'text_1_hour' => '1 Hora',
        'text_3_hours' => '3 Horas',
        'text_6_hours' => '6 Horas',
        'text_12_hours' => '12 Horas',
        'text_24_hours' => '24 Horas',
        'text_3_days' => '3 Dias',
        'text_5_days' => '5 Dias',
        'text_1_week' => '1 Semana',
        'text_auto' => 'Automaticamente',
        'text_manual' => 'Manualmente',
        'text_miles' => 'Milhas',
        'text_kilometers' => 'Quilômetros',
        'text_chain_geocoder' => 'Corrente (Recomendado)',
        'text_google_geocoder' => 'Google Geocoding',
        'text_nominatim' => 'OpenStreetMap\'s Nominatim',
        'text_plain' => 'Texto Simple',
        'text_html' => 'HTML',
        'text_sendmail' => 'Sendmail',
        'text_smtp' => 'SMTP',
        'text_log_file' => 'Arquivo de Log',
        'text_mailgun' => 'Mailgun',
        'text_postmark' => 'Postmark (Requer Drivers de Extensão de Terceiros)',
        'text_ses' => 'SES (Requires the Third-Party Drivers Extension)',
        'text_mail_no_encryption' => 'Sem criptografia',
        'text_mail_tls_encryption' => 'TLS',
        'text_mail_ssl_encryption' => 'SSL',
        'text_test_email_message' => 'This is a test email. If you\'ve received this, it means emails are working in TastyIgniter.',
        'text_to_customer' => 'Ao cliente',
        'text_to_admin' => 'Para o restaurante',
        'text_to_location' => 'Para o local',
        'text_send_test_email' => 'Enviar email de teste',
        'text_internal_sequence_prefix' => 'Prefixo mais sequência de numeração interna',
        'text_openexchangerates' => 'Taxa de Câmbio Aberto',
        'text_fixerio' => 'Fixer.io',
        'label_site_name' => 'Nome do restaurante',
        'label_site_email' => 'E-mail do restaurante',
        'label_site_logo' => 'Logotipo de restaurante',
        'label_timezone' => 'Fuso horário padrão',
        'label_currency_converter' => 'Conversor de Moedas Padrão',
        'label_currency_converter_oer_api_key' => 'Conversor de Moedas (Open Exchange Rates API) App ID',
        'label_currency_converter_fixer_api_key' => 'Conversor de Moedas (Fixer.io API) App ID',
        'label_currency_refresh_interval' => 'Intervalo de atualização das taxas de câmbio',
        'label_detect_language' => 'Detectar o idioma do navegador',
        'label_customer_group' => 'Grupo de clientes',
        'label_country' => 'País',
        'label_maps_api_key' => 'Chave de API do Google Maps',
        'label_distance_unit' => 'Unidade de distância',
        'label_default_geocoder' => 'Geocoder padrão',
        'label_mail_logo' => 'Logo',
        'label_sender_name' => 'Nome do Rementente',
        'label_sender_email' => 'Email do Remetente',
        'label_protocol' => 'Protocolo do E-mail',
        'label_smtp_host' => 'Servidor SMTP',
        'label_smtp_port' => 'Porta SMTP',
        'label_smtp_user' => 'Usuário SMTP',
        'label_smtp_pass' => 'Senha do SMTP',
        'label_smtp_encryption' => 'Protocolo de criptografia',
        'label_test_email' => 'E-mail de teste',
        'label_mailgun_domain' => 'Domínio do Mailgun',
        'label_mailgun_secret' => 'Mailgun segredo',
        'label_postmark_token' => 'Postmark token',
        'label_ses_key' => 'Chave SES',
        'label_ses_secret' => 'SES Segredo',
        'label_ses_region' => 'SES region',
        'label_permalink' => 'Link permanente',
        'label_enable_request_log' => 'Registrar Requisições Inválidas',
        'label_maintenance_mode' => 'Modo de Manutenção',
        'label_maintenance_message' => 'Mensagem de Manutenção',
        'label_activity_log_timeout' => 'Limpar o Log de atividades mais antigo que',
        'alert_email_sending' => 'Enviando e-mail...',
        'alert_email_sent' => 'E-mail enviado para %s',
        'alert_settings_missing_model' => 'Falta o modelo definido %s.',
        'alert_settings_not_found' => 'Configurações %s não foi encontrado.',
        'alert_settings_errors' => 'Clique para corrigir os itens de configuração requeridos em falta.',
        'alert_delete_setup_files' => '<b>ATENÇÃO!</b> Exclua os arquivos de configuração para impedir que outra pessoa substitua seu site.',
        'help_timezone' => 'Fuso horário padrão. Escolha uma cidade no mesmo fuso horário que o seu restaurante.',
        'help_detect_language' => 'Ative ou desative a detecção de idioma do navegador do usuário. Se ativado, seu site será traduzido para o idioma do navegador.',
        'help_maps_api_key' => 'É necessária uma chave de API para usar o Google Maps e/ou Geocodificação. <a target="_blank" href="https://developers.google.com/maps/documentation/javascript/get-api-key#get-an-api-key">Onde posso encontrar minha chave de API do Google Maps?</a> Habilitar Google Maps Geocoding API e Google Maps JavaScript API na sua conta do desenvolvedor do Google',
        'help_default_geocoder' => 'Diga ao sistema qual serviço de geocodificação deve ser usado quando a geocodificação for endereçada. \'Chain\' é um geo-codificador especial que executa tanto o google quanto o geo codificador de mapas de rua abertos e pára quando obtém uma resposta válida.',
        'help_currency_converter_oer_api' => 'Você pode <a target="_blank" href="https://openexchangerates.org/signup/">se inscrever aqui</a> para sua API de Taxas de Câmbio Aberto.',
        'help_currency_converter_fixer_api' => 'Você pode <a target="_blank" href="https://fixer.io/signup/">se inscrever aqui</a> para a sua API Fixer.io.',
        'help_special_category' => 'Selecione qual categoria usar automaticamente para menus especiais',
        'help_default_location' => 'Escolha ou adicione um novo local para definir como seu local principal/padrão.',
        'help_delete_thumbs' => 'Isto irá apagar todas as miniaturas criadas. Observe que as miniaturas são criadas automaticamente.',
        'help_media_max_size' => 'O tamanho máximo (em kilobytes) para o arquivo ao carregar.',
        'help_media_extensions' => 'The allowed file extensions for uploaded files. Multiple extensions can be separated by commas.',
        'help_media_upload' => 'Habilitar ou desabilitar o upload de arquivo',
        'help_media_new_folder' => 'Habilitar ou desabilitar a criação de pasta',
        'help_media_copy' => 'Habilitar ou desabilitar a cópia de arquivo/pasta',
        'help_media_move' => 'Habilitar ou desabilitar a movimentação de arquivo/pasta',
        'help_media_rename' => 'Habilitar ou desabilitar a renomeação de arquivo/pasta',
        'help_media_delete' => 'Habilitar ou desabilitar a exclusão de arquivo/pasta',
        'help_mail_logo' => 'Upload logo to display in emails',
        'help_enable_request_log' => 'Registrar solicitações incorretas de navegadores, como erro 404.',
        'help_maintenance' => 'Habilite para impedir que os clientes visualizem sua loja. A mensagem de manutenção será exibida para os clientes exceto para o administrador logado.',
        'help_activity_log_timeout' => 'Elimina todas as atividades registradas mais antigas que o número de dias especificado',
        'text_tab_language' => 'Línguas',
        'text_tab_currency' => 'Moedas',
        'text_tab_country' => 'Países',
        'text_tab_desc_status' => 'Manage your order and reservation statuses.',
        'text_tab_desc_language' => 'Manage languages available on your site.',
        'text_tab_desc_currency' => 'Manage currencies available on your site.',
        'text_tab_desc_country' => 'Manage countries available on your site.',
        'help_language' => 'You can set the default language for your site from the <em>Manage > Settings > Languages</em> page',
        'help_site_currency' => 'You can set the default currency for your site from the <em>Manage > Settings > Currencies</em> page',
    ],
    'system_logs' => [
        'button_empty' => '<i class="fa fa-eraser"></i>&nbsp;&nbsp;Logs Vazios',
        'button_request_logs' => '<i class="fa fa-globe"></i>&nbsp;&nbsp;Logs de Requisições',
        'text_title' => 'Logs',
    ],
    'themes' => [
        'text_title' => 'Temas',
        'text_edit_title' => 'Tema: Personalizar',
        'text_source_title' => 'Tema: Editar Modelo',
        'text_delete_title' => 'Tema: Apagar',
        'text_form_name' => 'Tema',
        'text_tab_customize' => 'Personalizar',
        'text_tab_markup' => 'Markup',
        'text_tab_php_section' => 'Seção PHP',
        'text_tab_meta' => 'Meta',
        'text_tab_components' => 'Componentes',
        'text_empty' => 'Não há temas disponíveis.',
        'text_select_file' => 'Selecione um modelo [%s] para editar',
        'text_is_default' => 'Ativado',
        'text_set_default' => 'Ativar',
        'text_author' => 'por',
        'text_version' => 'Versão',
        'text_theme_is_active' => '. Você não pode excluir um tema ativo.',
        'text_files' => 'arquivos',
        'text_files_data' => 'arquivos e dados',
        'text_locked_child' => 'Tema bloqueado: criar um tema filho',
        'label_code' => 'Código',
        'label_template' => 'Modelo',
        'label_file' => 'Nome do arquivo do modelo',
        'label_title' => 'Título',
        'label_layout' => 'Layout',
        'label_permalink' => 'Link permanente',
        'label_component' => 'Componente',
        'label_component_alias' => 'Component Alias',
        'label_component_status' => 'Situação do Componente',
        'label_override_partial' => 'Component Partial To Override',
        'label_delete_data' => 'Excluir dados',
        'label_copy_data' => 'Copiar Dados',
        'label_type_page' => 'Páginas',
        'label_type_partial' => 'Parciais',
        'label_type_layout' => 'Layouts',
        'label_type_content' => 'Conteúdo',
        'button_browse' => '<i class="fa fa-globe"></i>&nbsp;&nbsp;Browse more themes&nbsp;&nbsp;<i class="fa fa-external-link-alt"></i>',
        'button_source' => '<i class="fa fa-file"></i>&nbsp;&nbsp;Editar arquivos de modelo',
        'button_customize' => '<i class="fa fa-paint-brush"></i>&nbsp;&nbsp;Personalizar',
        'button_child' => '<i class="fa fa-child"></i>&nbsp;&nbsp;Criar tema filho',
        'button_new_source' => 'Novo(a) %s',
        'button_rename_source' => 'Renomear %s',
        'button_delete_source' => 'Excluir %s',
        'button_delete' => 'Excluir',
        'button_yes_delete' => 'Sim, excluir',
        'button_yes_copy' => 'Sim, copiar',
        'button_return_to_list' => 'Não, voltar para a lista',
        'help_component_alias' => 'DO NOT CHANGE. Except you know what you are doing.',
        'help_override_partial' => 'The selected component partial file will be copied to the active theme partial directory under <code>%s</code>.',
        'error_config_no_found' => 'Ocorreu um erro, o arquivo de registro do tema não foi encontrado',
        'error_theme_exists' => 'O tema já existe',
        'alert_delete_warning' => 'Você está prestes a excluir o %s do tema <b>%s</b>',
        'alert_delete_confirm' => 'Tem certeza de que deseja excluir o associado %s? Isso não pode ser desfeito!',
        'alert_theme_locked' => 'Este é um tema bloqueado. alterações são restritas, crie um tema filho para fazer alterações.',
        'alert_theme_path_locked' => 'Este modelo pertence a um tema bloqueado, essas ações estão restritas.',
        'alert_changes_confirm' => 'Versões conflitantes, o arquivo modelo foi alterado. Recarregue a página para continuar.',
        'alert_customize_not_active' => 'You can only customize an active theme.',
        'label_is_active' => 'Is Active',
        'label_hidden' => 'Hidden',
        'button_choose' => 'Choose a component to attach',
        'button_reset_to_default' => 'Reset to Defaults',
        'help_components' => 'Render the component on a layout or page by adding <code>@themeComponent(&#x27;componentAlias&#x27;)</code> or <code>&#x3C;livewire:component-code /&#x3E;</code> to the markup. Learn more <a href="https://tastyigniter.com/docs/extend/components">here</a>.',
        'alert_component_partial_not_found' => 'The selected component partial does not exist in the component directory',
        'alert_no_publish_custom' => 'Publishing custom theme files requires a child theme located within the themes directory',
        'alert_publish_confirm' => 'Are you sure you wish to publish the theme files? This will overwrite the existing theme files.',
    ],
    'updates' => [
        'text_title' => 'Atualizações',
        'text_browse_title' => 'Navegar %s',
        'text_title_carte' => 'Seu Carté',
        'text_tab_title_extensions' => 'Extenções',
        'text_tab_title_themes' => 'Temas',
        'text_tab_title_languages' => 'Línguas',
        'text_ignore' => 'Ignorar',
        'text_search' => 'Search to install %s from the TastyIgniter marketplace',
        'text_popular_title' => 'Recomendado %s',
        'text_no_updates' => 'Não há atualizações disponíveis',
        'text_update_found' => '%s atualização(ões) disponíveis(s)',
        'text_update_ignored' => '%s atualização(ões) ignoradas',
        'text_item_update_summary' => 'Atualizar da versão %s para <b>%s</b>',
        'label_meta_code' => 'Meta Code',
        'label_meta_type' => 'Meta Type',
        'label_meta_version' => 'Versão Meta',
        'label_meta_hash' => 'Meta Hash',
        'label_meta_description' => 'Meta Descrição',
        'label_meta_step' => 'Meta Step',
        'label_meta_action' => 'Meta Action',
        'label_meta_items' => 'Meta Items',
        'progress_enable_maintenance' => 'Ativando o modo de manutenção&#8230;',
        'progress_disable_maintenance' => 'Restaurando/Desabilitando Modo de Manutenção&#8230;',
        'button_browse' => '<i class="fa fa-globe"></i>&nbsp;&nbsp;Navegar %s',
        'button_check' => '<i class="fa fa-refresh"></i>&nbsp;&nbsp;Check Updates',
        'button_updates' => '<i class="fa fa-refresh"></i>&nbsp;&nbsp;Atualizações',
        'button_update' => '<i class="fa fa-check"></i>&nbsp;&nbsp;Atualização',
        'button_recommended_extension' => 'Install recommended extensions...',
        'button_recommended_theme' => 'Install a recommended theme...',
        'button_install' => 'Install Selected...',
        'alert_item_to_ignore' => 'Select item(s) to ignore.',
        'alert_no_carte_key' => 'No carte key specified.',
        'alert_no_items' => 'No item(s) specified.',
        'button_attach_carte' => '<i class="fa fa-key"></i>&nbsp;&nbsp;Attach Carté Key',
        'help_carte_key' => 'A Carte key is required to add and update item from the TastyIgniter Marketplace. <br>Get one by creating a site from your <a href="%s" target="_blank">TastyIgniter Account</a>, if you haven\'t already. For more information, see the <a href="%s" target="_blank">Carté Key Guide</a>',
        'alert_item_to_update' => 'Select item(s) to update.',
        'notify_new_update_found_title' => 'Updates available.',
        'notify_new_update_found' => 'An update is available.',
        'notify_new_updates_found' => '<b>%s</b> updates available.',
        'text_last_checked' => 'Last checked',
        'text_checking_updates' => 'Checking updates...',
        'label_meta_name' => 'Meta Name',
        'label_meta_package' => 'Meta Package',
        'progress_check' => 'Performing pre installation checks...',
        'progress_preinstall_ok' => 'Pre installation checks completed.<i class="fa fa-check fa-fw"></i>',
        'progress_install' => 'Updating composer requirements...',
        'progress_install_ok' => 'Updated composer requirements.<i class="fa fa-check fa-fw"></i>',
        'progress_install_version' => '    %s (%s => %s)',
        'progress_complete' => 'Finishing installation...',
        'progress_completed' => 'Finished installation successfully.<i class="fa fa-check fa-fw"></i>',
        'progress_composer_success' => '<i class="fa fa-check fa-fw"></i>&nbsp;&nbsp;&nbsp;Finished updating composer/composer successfully.&#8230;',
        'progress_core_success' => '<i class="fa fa-check fa-fw"></i>&nbsp;&nbsp;&nbsp;Finished updating core successfully.&#8230;',
        'progress_addons_success' => '<i class="fa fa-check fa-fw"></i>&nbsp;&nbsp;&nbsp;Finished updating extensions & themes successfully.&#8230;',
        'button_carte' => '<i class="fa fa-key"></i>&nbsp;&nbsp;Your Carté Key',
        'notify_no_update_found_title' => 'Não há atualizações disponíveis',
    ],
    'no_database' => [
        'label' => 'Foi encontrado um erro no banco de dados',
        'help' => 'Uma conexão com a base de dados é necessária. Verifique se a base de dados está devidamente configurada e migrada antes de tentar novamente.',
    ],
    'required' => [
        'config' => "Configuração usada em %s deve fornecer um valor '%s'.",
    ],
    'not_found' => [
        'config' => 'Não foi possível encontrar o arquivo de configuração %s definido para %s.',
        'class' => "Não foi possível encontrar '%s' em %s",
        'combiner' => "Não foi possível encontrar arquivos '%s'",
    ],
    'version' => 'Versão',
];
