<?php
return [
    'alert_error_try_again' => 'Ocorreu um erro. Por favor, tente novamente.',
    'alert_warning_confirm' => 'Isto não pode ser desfeito! Tem certeza que quer fazer isso?',
    'text_my_account' => 'Minha conta',
    'text_information' => 'Informações',
    'text_follow_us' => 'Siga-nos:',
    'text_maintenance_enabled' => 'Manutenção ativada',
    'menu_menu' => 'Visualizar menu',
    'menu_reservation' => 'Reserva',
    'menu_login' => 'Acesso',
    'menu_logout' => 'Sair',
    'menu_register' => 'Registrar-se',
    'menu_my_account' => 'Minha conta',
    'menu_account' => 'Principal',
    'menu_detail' => 'Editar detalhes',
    'menu_address' => 'Catálogo de endereços',
    'menu_recent_order' => 'Pedidos recentes',
    'menu_recent_reservation' => 'Reservas recentes',
    'menu_locations' => 'Nossos locais',
    'menu_contact' => 'Fale Conosco',
    'menu_admin' => 'Administrador',
    'alert_custom_error' => 'Algo deu errado e a página não pode ser exibida',
    'alert_no_search_query' => '<p class="alert-danger">Digite o endereço completo, para verificar se nós podemos entregar para você.</p>',
    'alert_info_outdated_browser' => 'Você está usando um navegador desatualizado. <a href="http://browsehappy.com/">Atualize seu navegador hoje</a> ou <a href="http://www.google.com/chromeframe/?redirect=true"> instalar o Google Chrome</a> para melhor uso deste site.',
    'components' => [
        'button_new' => 'Adicionar componente',
        'button_edit' => 'Editar componente',
        'button_delete' => 'Excluir Componente',
    ],
    'media_manager' => [
        'text_title' => 'Gerenciador de mídia',
        'text_heading' => 'Gerenciador de mídia',
        'text_empty' => 'Nenhum arquivo encontrado.',
        'text_read_only' => 'Somente leitura',
        'text_read_write' => 'Leitura e gravação',
        'text_footer_note' => '%s itens selecionados, %s',
        'text_no_access' => 'Sem acesso',
        'text_items' => 'Itens',
        'text_choose' => 'Escolher',
        'text_attach' => 'Anexar',
        'text_sort_by' => 'Ordenar Por',
        'text_filter_search' => 'Pesquisar arquivos e pastas...',
        'text_new_folder' => 'Nova pasta',
        'text_rename_folder' => 'Renomear pasta',
        'text_delete_folder' => 'Excluir pasta',
        'text_move_folder' => 'Mover pasta',
        'text_items_selected' => 'Itens selecionados',
        'text_folder_name' => 'Nome da pasta',
        'text_file_name' => 'Nome do Arquivo',
        'button_upload' => 'Enviar',
        'button_preview' => 'Pré-visualizar',
        'button_rename' => 'Renomear',
        'button_move' => 'Mover',
        'button_copy' => 'Copiar',
        'button_delete' => 'Excluir',
        'button_cancel' => 'Cancelar',
        'label_name' => 'Nome',
        'label_date' => 'Data',
        'label_size' => 'Tamanho',
        'label_type' => 'Tipo',
        'label_path' => 'Caminho',
        'label_url' => 'URL',
        'label_dimension' => 'Dimensões',
        'label_modified_date' => 'Data de modificação',
        'label_extension' => 'Extensões',
        'label_permission' => 'Permissões',
        'label_filter_all' => 'Everything',
        'label_filter_image' => 'Imagens',
        'label_filter_video' => 'Videos',
        'label_filter_audio' => 'Audios',
        'label_filter_document' => 'Documents',
        'alert_invalid_file_name' => 'Nome de aquivo ou pasta inválido',
        'alert_invalid_new_file_name' => 'Nome de aquivo ou pasta inválido',
        'alert_file_exists' => 'Pasta já existente',
        'alert_file_not_writable' => 'Permissão negada: O arquivo não é gravável.',
        'alert_file_not_found' => 'Permissão negada ou arquivo não encontrado',
        'alert_extension_not_allowed' => 'A extensão %s não é permitida.',
        'alert_permission' => 'Aviso: Você não tem permissão para %s, contate o administrador do sistema.',
        'alert_new_folder_disabled' => 'Criação de nova pasta está desativada, verifique as configurações do Gerenciador de imagem/mídia.',
        'alert_rename_disabled' => 'Renomear arquivo/pasta está desabilitado, verifique as configurações do Gerenciador de imagem/mídia.',
        'alert_success_new_folder' => 'Pasta criada com sucesso',
        'alert_success_rename' => 'Arquivo/pasta renomeado com sucesso',
        'alert_error_upload' => 'Algo deu errado ao salvar o arquivo, por favor tente novamente.',
        'alert_success_upload' => 'Carregado com sucesso',
        'alert_upload_disabled' => 'O carregamento está desabilitado, verifique as configurações do gerenciador de imagem/mídia.',
        'alert_invalid_path' => 'O caminho especificado para o carregamento é inválido',
        'alert_copy_disabled' => 'A cópia de arquivos/pastas está desabilitada, verifique as configurações do Gerenciador de imagem/mídia.',
        'alert_select_copy_folder' => 'Por favor, selecione o destino, a fonte e o arquivo/pasta que você deseja copiar.',
        'alert_select_copy_file' => 'Por favor, selecione o arquivo/pasta que deseja copiar.',
        'alert_select_move_folder' => 'Por favor, selecione o destino, a fonte e o arquivo/pasta que você deseja mover.',
        'alert_select_move_file' => 'Por favor, selecione o arquivo/pasta que deseja mover.',
        'alert_success_copy' => 'Arquivo/pasta copiado com sucesso',
        'alert_move_disabled' => 'Mover arquivos/pastas está desabilitado, verifique as configurações do Gerenciador de imagem/mídia.',
        'alert_success_move' => 'Arquivo/Pasta movida com sucesso',
        'alert_delete_disabled' => 'A exclusão de arquivos/pastas está desabilitada, verifique as configurações do Gerenciador de imagem/mídia.',
        'alert_select_delete_file' => 'Por favor, selecione o arquivo/pasta que deseja excluir.',
        'alert_success_delete' => 'Arquivo %s excluído com êxito',
        'alert_select_item_to_attach' => 'Select an item to attach.',
        'alert_only_attach_to_saved' => 'You can only attach media to a saved form.',
        'alert_missing_mediable' => 'You must define a media tag %s within $mediable property in %s to attach a media.',
        'label_attachment_title' => 'Título',
        'label_attachment_description' => 'Descrição',
        'label_attachment_properties' => 'Propriedades personalizadas',
        'label_attachment_property_key' => 'Key',
        'label_attachment_property_value' => 'Valor',
        'help_existing_files' => 'Arquivo/pasta existente não será substituída',
        'help_attachment_config' => 'Adicionar propriedades personalizadas para este anexo',
        'alert_file_name_required' => 'Por favor, digite um novo nome para a pasta',
    ],
    'home' => [
        'title' => 'Pedidos online',
        'text_step_one' => 'Procurar',
        'text_step_two' => 'Escolher',
        'text_step_three' => 'Pagar em dinheiro ou cartão',
        'text_step_four' => 'Aproveite',
        'text_step_search' => 'Encontre e selecione um restaurante próximo a você, digitando o seu endereço completo.',
        'text_step_choose' => 'Vários menus para navegar e encontrar o alimento que você deseja.',
        'text_step_pay' => 'É rápido, fácil e seguro. Pagamento em dinheiro na entrega ou via cartão de crédito.',
        'text_step_enjoy' => 'A comida é preparada e entregue à sua porta ou pronto para coleta no restaurante.',
    ],
    'local' => [
        'text_tab_menu' => 'Menu',
        'text_tab_review' => 'Avaliações',
        'text_tab_info' => 'Informação',
        'text_tab_gallery' => 'Galeria',
        'menus' => [
            'title' => 'Menu',
        ],
        'info' => [
            'title' => 'Informação',
        ],
        'gallery' => [
            'title' => 'Galeria',
        ],
        'reviews' => [
            'title' => 'Avaliações',
        ],
    ],
    'checkout' => [
        'title' => 'Finalizar',
        'success' => [
            'title' => 'Confirmação de compra',
        ],
    ],
    'reservation' => [
        'title' => 'Reserva',
        'success' => [
            'title' => 'Confirmação de reserva',
        ],
    ],
    'cart' => [
        'title' => 'Carrinho',
    ],
    'locations' => [
        'title' => 'Locais',
    ],
    'contact' => [
        'title' => 'Contato',
    ],
    'pages' => [
        'title' => 'Páginas',
        'text_theme_page' => 'Página do tema',
    ],
    'permissions' => [
        'name' => 'Front-end',
        'media_manager' => 'Carregar e gerenciar o conteúdo de mídia',
        'themes' => 'Ativar, desativar, configurar e modificar temas do front-end',
    ],
    'account' => [
        'title' => 'Conta',
        'login' => [
            'title' => 'Acesso',
            'text_login' => 'Iniciar Sessão',
            'text_register' => 'Registre-se no <small>É fácil e sempre será.</small>',
            'text_forgot' => 'Esqueceu a senha?',
            'text_login_register' => 'Já se registrou? <a href="%s">Entrar</a>',
            'button_login' => 'Acesso',
            'button_register' => 'Registrar-se',
        ],
        'register' => [
            'title' => 'Registrar-se',
        ],
        'address' => [
            'title' => 'Conta',
        ],
        'settings' => [
            'title' => 'Configurações',
        ],
        'orders' => [
            'title' => 'Pedidos',
        ],
        'reservations' => [
            'title' => 'Reservas',
        ],
        'reviews' => [
            'title' => 'Avaliações',
        ],
        'inbox' => [
            'title' => 'Caixa de entrada',
        ],
        'reset' => [
            'title' => 'Redefinição de senha',
            'text_heading' => 'Redefinição de senha',
        ],
    ],
    'not_found' => [
        'layout_name' => 'Layout [%s] não encontrado',
        'page_label' => 'Página não encontrada',
        'page_message' => 'A página solicitada não foi encontrada',
        'active_theme' => 'Não foi possível carregar o tema ativo',
        'controller_action' => 'Ação [%s] não encontrada no controle [%s]',
        'layout' => 'O layout [%s] não foi encontrado.',
        'component' => 'O componente [%s] não foi encontrado.',
        'partial' => 'A parte [%s] não foi encontrada.',
        'content' => 'O conteúdo [%s] não foi encontrado.',
        'method' => 'O método [:method] não foi encontrado em [:name].',
        'ajax_handler' => 'Manipulador Ajax [%s] não encontrado.',
    ],
    'settings' => [
        'text_tab_media_manager' => 'Mídia',
        'text_tab_desc_media_manager' => 'Configurar carregamento de mídia, copiar, renomear as configurações.',
    ],
    'alert_success' => '%s com sucesso.',
    'alert_error' => 'Ocorreu um erro, %s.',
    'alert_error_nothing' => 'Ocorreu um erro, nada %s.',
    'text_free' => 'Gratuito',
    'text_minutes' => 'minutos',
];
